# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'MVPConf.WebApi.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1
  inputs:
   versionSpec: '5.x'

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: MSBuild@1
  inputs:
    solution: 'MVPConf.WebApi.sln'
    msbuildArguments: '/p:OutputPath=$(build.binariesdirectory)/$(BuildConfiguration)/Output'
    
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'MVPConf.Application.Test\MVPConf.Application.Test.csproj'
  condition: succeeded()

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(build.binariesdirectory)/$(BuildConfiguration)/Output'
    ArtifactName: 'webapi-artifact'
  condition: succeeded()